# Generated by Django 4.2.10 on 2024-04-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import negligent_octopus.budget.models
import negligent_octopus.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_transaction_destination_account_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportActivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "load",
                    models.FileField(
                        upload_to=negligent_octopus.budget.models.upload_activo_import_to,
                        validators=[
                            negligent_octopus.utils.validators.FileExtensionValidator(
                                ("csv", "xsls")
                            )
                        ],
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activo Import",
                "verbose_name_plural": "Activo Imports",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
    ]
