# Generated by Django 4.2.10 on 2024-04-18 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_transaction_destination_account_name"),
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedActivoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date_of_movement", models.DateField()),
                ("date_of_process", models.DateField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("value", models.FloatField()),
                ("balance", models.FloatField()),
                ("validated", models.BooleanField(default=False)),
                (
                    "loaded_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="budget.importactivo",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imported Activo Transaction",
                "verbose_name_plural": "Imported Activo Transactions",
                "ordering": ["-date_of_process", "-created"],
                "abstract": False,
            },
        ),
    ]
