# Generated by Django 4.2.10 on 2024-05-06 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import negligent_octopus.budget.models
import negligent_octopus.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_transaction_destination_account_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0003_alter_importactivo_load_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleImportedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("amount", models.FloatField()),
                ("balance", models.FloatField()),
                ("validated", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Simple Imported Transaction",
                "verbose_name_plural": "Simple Imported Transactions",
                "ordering": ["-date", "-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SimpleTransactionsImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "load",
                    models.FileField(
                        upload_to=negligent_octopus.budget.models.upload_import_file_to,
                        validators=[
                            negligent_octopus.utils.validators.FileExtensionValidator(
                                ("csv", "xsls", "xls", "xlsx", "xlsm", "xlsb")
                            )
                        ],
                    ),
                ),
                ("processed", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Simple Transactions Import",
                "verbose_name_plural": "Simple Imports",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="importedactivotransaction",
            name="loaded_from",
        ),
        migrations.RemoveField(
            model_name="importedactivotransaction",
            name="transaction",
        ),
        migrations.DeleteModel(
            name="ImportActivo",
        ),
        migrations.DeleteModel(
            name="ImportedActivoTransaction",
        ),
        migrations.AddField(
            model_name="simpleimportedtransaction",
            name="loaded_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="budget.simpletransactionsimport",
            ),
        ),
        migrations.AddField(
            model_name="simpleimportedtransaction",
            name="transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.transaction",
            ),
        ),
    ]
