# Generated by Django 4.2.10 on 2024-05-06 10:57

from django.db import migrations, models
import negligent_octopus.budget.models
import negligent_octopus.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_simpleimportedtransaction_simpletransactionsimport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpletransactionsimport",
            name="load",
            field=models.FileField(
                upload_to=negligent_octopus.budget.models.upload_import_file_to,
                validators=[
                    negligent_octopus.utils.validators.FileExtensionValidator(
                        ("csv", "xsls", "xls", "xlsx", "xlsm", "xlsb")
                    )
                ],
            ),
        ),
    ]
