# Generated by Django 4.2.10 on 2024-05-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_alter_simpletransactionsimport_load"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simpleimportedtransaction",
            name="loaded_from",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="budget.simpletransactionsimport",
            ),
        ),
    ]
