# Generated by Django 4.2.10 on 2024-03-18 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-timestamp", "-created"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
        migrations.AddField(
            model_name="transaction",
            name="balance",
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("timestamp", "created")},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
    ]
