# Generated by Django 4.2.10 on 2024-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_transaction_account_add_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
