# Generated by Django 4.2.10 on 2024-03-18 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_transaction_account_add_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="initial_balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("name", "owner")},
        ),
    ]
