# Generated by Django 4.2.10 on 2024-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_transaction_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="destination_account_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
