# Generated by Django 4.2.10 on 2024-05-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_transaction_destination_account_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_removed",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_removed",
        ),
    ]
